services:

  db:
    container_name: users_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/db_data
      - ./src/db/schemas/user.sql:/docker-entrypoint-initdb.d/user.sql

    ports:
      - 8888:5432
volumes:
  db_data: